### ISSUE TITLE
[Feature] Ability to add custom content to header or footer of Modal

### ISSUE THREAD

**Issue by Morgul** [yuche/vue-strap#11]
Currently, the modal only allows custom content in the body. The vast majority of my use cases involve, at a minimum, changing the names of the button in the footer, and adding an icon to the title. So, my proposal would be to change the template to this:

```html
<template>
  <div class="modal fade" role="dialog"
    v-class="
    fade:effect === 'fade',
    zoom:effect === 'zoom'"
    >
    <div class="modal-dialog" role="document"
      v-style="width: width + 'px'
      ">
      <div class="modal-content">
        <content select=".modal-header">
          <div class="modal-header">
            <button type="button" class="close" v-on='click:close'><span>&times;</span></button>
            <h4 class="modal-title" >{{title}}</h4>
          </div>
        </content>
        <content select=".modal-body">
          <div class="modal-body"></div>
        </content>
        <content select=".modal-footer">
            <div class="modal-footer" v-show="footer">
            <button type="button" class="btn btn-default" v-on='click:close'>Close</button>
            <button type="button" class="btn btn-primary" v-on='click:callback'>Save changes</button>
          </div>
        </content>
      </div>
    </div>
  </div>
</template>
```

Which means a modal could be defined like this:

```html
<modal show="showModal">
    <div class="modal-header">
        <h4 class="modal-title"><i class="fa fa-ge"></i> Modal title</h4>
    </div>
    <div class="modal-body">
        <p>So, this is a thing.</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-primary" v-on="click: showModal = false">Save changes</button>
        <button type="button" class="btn btn-secondary" v-on="click: showModal = false">Close</button>
    </div>
</modal>
```

This does bring up the issue that closing a modal is a little difficult if you override footers, but you can handle that with `v-ref`. Assuming we add `v-ref="coolModal"` to the above modal definition, the user can do:

```javascript
var app = new Vue({
    methods: {
        close: function(){ this.$.coolModal.close(); }
    }
});
```

I'm not sure of a better way to handle this case in Vue, but I'd rather have to deal with that, then not be allowed to add content, or change buttons on modals.

**Comment by Morgul** [comment]
Minor disclaimer: There might be some syntax issues, I'm new to Vue, and jumped right into `1.0.0-beta`, so I had to look up the equivalent syntax for `v0.12`.

I've currently implemented a Bootstrap modal component on my own (before I heard about this project) for Vue `v1.0.0`, and Bootstrap 4. If nothing else, it provides a working example of the idea I described above. Let me know if you want to see it, and I'll push the code out somewhere.

**Comment by yuche** [comment]
Good idea. Your code works fine except generate two `div.modal-body` tag. Change the code like this like this may work (You can pull a request and I will merge) :

```HTML
<template>
  <div class="modal fade" role="dialog"
    v-class="
    fade:effect === 'fade',
    zoom:effect === 'zoom'"
    >
    <div class="modal-dialog" role="document"
      v-style="width: width + 'px'
      ">
      <div class="modal-content">
        <content select=".modal-header">
          <div class="modal-header">
            <button type="button" class="close" v-on='click:close'><span>&times;</span></button>
            <h4 class="modal-title" >{{title}}</h4>
          </div>
        </content>
        <content select=".modal-body">
          <div class="modal-body"></div>
         </content>
        <content select=".modal-footer">
            <div class="modal-footer" v-show="footer">
            <button type="button" class="btn btn-default" v-on='click:close'>Close</button>
            <button type="button" class="btn btn-primary" v-on='click:callback'>Save changes</button>
          </div>
        </content>
      </div>
    </div>
  </div>
</template>
```

And I want to see your implementation if you don't mind.

**Comment by Morgul** [comment]
@yuche My implementation is here:

https://github.com/Morgul/vueboot/blob/master/src/modal/modal.vue

There's some additional features my implementation has:
* `backdrop` - If `true`, includes a modal-backdrop element. Alternatively, specify the string 'static' for a backdrop which doesn't close the modal on click.
* `keyboard` - Should the modal close when escape key is pressed.
* `animation` - If `false`, disable animations.

I'd love to see at least `keyboard` and `backdrop` included eventually as well.

**Comment by Morgul** [comment]
@yuche Looks like the documentation hasn't been updated yet, despite this being released.
