### ISSUE TITLE
Aside.vue component have some error,have you fix it, help me? 

### ISSUE THREAD

**Issue by ChacesXia** [yuche/vue-strap#144]
this is error
`in ./~/vue-strap/src/utils/EventListener.js
Module parse failed: E:\coding\vue-center\node_modules\vue-strap\src\utils\EventListener.js Line 29: Unexpected token
You may need an appropriate loader to handle this file type.
| }
| 
| export default EventListener
| 
 @ ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-strap/src/Aside.vue 7:21-56
ERROR in ./~/vue-strap/src/utils/getScrollBarWidth.js
Module parse failed: E:\coding\vue-center\node_modules\vue-strap\src\utils\getScrollBarWidth.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| export default ()=> {
|   if (document.documentElement.scrollHeight <= document.documentElement.clientHeight) {
|     return 0
 @ ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-strap/src/Aside.vue 11:25-64`

this is my SideBar.vue component 
`<template>
	<button class="btn btn-danger btn-lg" @click="showLeft=true">
		sidebar
	</button>

	<sidebar :show.sync="showLeft" placement="left" header="Title" :width="350">
		<ul>
			<li v-for="item in items">
				{{item.message}}
			</li>
		</ul>

	</sidebar>

</template>

<script type="text/javascript">

import sidebar from "vue-strap/src/Aside.vue"
// var sidebar = require('vue-strap/src/Aside');
var items=[
	{message:"foo"},
	{message:"bar"}
]
export default {
	data(){
		return{
			items,
		}
	},
	components:{
		sidebar
	}
}
</script>`

**Comment by ChacesXia** [comment]
error
![image](https://cloud.githubusercontent.com/assets/15275744/13736815/e47fbc48-e9f2-11e5-8817-5a1212e74296.png)

`import sidebar from "vue-strap/src/Aside.vue"
// var sidebar = require('vue-strap/src/Aside');
var items=[
	{message:"foo"},
	{message:"bar"}
]
export default {
	data(){
		return{
			items,
		}
	},
	components:{
		sidebar
	}
}`

**Comment by bvelastegui** [comment]
I resolve this problem, use:

```javascript
import Vue from 'vue'
var sidebar = require('vue-strap').aside

new Vue({
    components: { sidebar }
}).$mount('body')
```
