### ISSUE TITLE
require('vue-strap').modal is not working. pr #158 in progress

### ISSUE THREAD

**Issue by prog-rajkamal** [yuche/vue-strap#159]
current situation:

     require('vue-strap').modal //fails
     import {modal} from 'vue-strap' //fails

     require('vue-strap/src/main.js').modal //fails
     require('vue-strap/src/index.js').modal // works

after  #158  :

     require('vue-strap').modal //works
     import {modal} from 'vue-strap' //works

     require('vue-strap/src/main.js').modal //fails
     require('vue-strap/src/index.js').modal // works

I am using vueify, broweserify with laravel-elixir

**Comment by mrgodhani** [comment]
Doing `import { tooltip } from 'vue-strap'` gave me like 40 terminal notifications with errors.

**Comment by prog-rajkamal** [comment]
@mrgodhani the pr has been merged but not released so for now, you have to do the changes manually, whenever the next version is released

the changes are to be done in `node_modules/vue-strap/package.json`

 1.  updating `main` 
    original:  `"main": "dist/vue-strap.js"`
    correct:  ` "main": "src/index.js"`

 2. updating browserify transform

original:

      "browserify": {
           "transform": [
           [
              "vueify"
          ] 
        }
correct:

     "browserify": {
          "transform": [
        [
           "babelify", { "presets": ["es2015"] }
       ],
       [
           "vueify"
       ]
       }



it will work after those changes.

**Comment by mrgodhani** [comment]
@prog-rajkamal that doesn't work either. It gives following :+1: 

`
[12:23:14] gulp-notify: [Laravel Elixir] Browserify Failed!: 'import' and 'export' may appear only with 'sourceType: module'

/Users/meetgodhani/Desktop/Crowdlinker/laterpost/node_modules/vue-strap/src/index.js:1
import alert from './Alert.vue'
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
`

**Comment by prog-rajkamal** [comment]
oh forgot about that one.

 in node_modules/vue-strap/package.json, add lines as https://github.com/yuche/vue-strap/commit/438c0f72bae216f6a8e568f654929f55e26ccd0c

**Comment by smargh** [comment]
A patch release even with just that commit would be incredibly valuable to me and my team, FWIW.

**Comment by prog-rajkamal** [comment]
@smargh I totally agree with you. in fact that 3 line commit was the entire reason, I made pull request in the first place.

**Comment by mrcsmcln** [comment]
Can we get this `npm publish`ed?

**Comment by vesper8** [comment]
yes pretty please we need a 1.0.9 :)

**Comment by prog-rajkamal** [comment]
Closing the issue because PR is merged

**Comment by edgarnadal** [comment]
I'm getting the same error.

Using version 1.0.11. Vueify + elixir

**Comment by prog-rajkamal** [comment]
@edgarnadal The commit was reversed in 1.0.10 because it was decided that `main` should be pointing to `dist` versions to avoid extra compiling . Due to a problem in bundling, it is not working correctly. 

the workaround is to use `require('vue-strap/src/index')`. that way we will be using vueify to compile it. 

Until module bundling problem is sorted out, this problem will stay.

**Comment by djfurman** [comment]
Thanks, @prog-rajkamal. I'm looking forward to the fix for this well.

Using your work around, I'm getting a new error.

```node_modules/vueify/lib/compiler.js:59
  Object.keys(config).forEach(function (key) {
         ^

TypeError: Cannot convert undefined or null to object
    at EventEmitter.compiler.applyConfig (node_modules/vueify/lib/compiler.js:59:10)
```

This is a new project with the following as my laravel-elixir-vueify browersify endpoint file.

```
let Vue = require('vue');
let VueResource = require('vue-resource');
require('vue-strap/src/index');
/*
	Import section for vue components
 */
// import { alert } from 'vue-strap/src/index';
/*
	Initialization of Vue extensions
 */
Vue.use(VueResource);

/*
	Setup for root vue instance
 */
let root_vue_instance = new Vue({
	el: '#app',

	// components: {
	// 	alert
	// },

	ready() {
		"use strict";
		console.log('This is going swimmingly! The root vue instance is loaded.');
	}
});
```

Is this something you've experienced before? I've done some basic googling, but I can't seem to find anything that helps.

**Comment by prog-rajkamal** [comment]
@djfurman Hi, I am sorry, but I can't help you much. My team has stopped using vue-strap and accordingly, I have stopped looking into this matter. 

FWIW, here are some things you can do. 
 - change `require` to `import` 
 babel had changed some setting in import/export and vue-strap uses import. Its possible that those changes are affecting you.

- revert to a previous vue-strap version and try again

Its possible that the bug is in vue-strap and it worked in previous versions. If that is the case, you should open an issue. 

- The quick hack I would use.
Copy and paste required component(s) to your project source. And use them as if you had written them instead. 

Note: some files require other files, but unless the error is present in the component you require, it will work without a hitch.

**Comment by djfurman** [comment]
Thanks @prog-rajkamal!

**Comment by dmitov** [comment]
This issue is till present.

**Comment by prog-rajkamal** [comment]
@dmitov The issue is present, but vue-strap team has acknowledged it and advised using webpack(vue-loader). Hence I have not re-opened this issue. But if you wish to, you can create a new issue.

If you wish to pursue this matter further, Here is some info.

The actual problem lies in bundling with webpack. webpack is generating umd bundles. which are not correctly working with browserify transforms.

**Comment by xscence** [comment]
Full of bugs. Will not use this. Soo bad work. And almost 90% of the things doesn't work. Keep the good work up.
