### ISSUE TITLE
Style not introduced

### ISSUE THREAD

**Issue by ph2-cst** [yuche/vue-strap#177]
use vue-cli and webpack.
why not bootstrap.css is not introduced.
everything is  work but style.

**Comment by yuche** [comment]
Try add this in your app.js:

require('bootstrap/less/bootstrap.less');

在 2016年4月26日 下午7:59:35, ph2-cst (notifications@github.com) 写到:

use vue-cli and webpack.
why not bootstrap.css is not introduced.
everything is work but style.

**Comment by ph2-cst** [comment]
well done.
use `require('bootstrap/less/bootstrap.less');`
error `Module not found: Error: Cannot resolve module 'less-loader'`

So I try to use `require('bootstrap/dist/css/bootstrap.min.css')` , and it's useful.

eh, I have not found bootstrap was introduced in vue-strap (./docs/), Why does it take effect?

**Comment by ph2-cst** [comment]
bootstrap.css is introduced in html
