### ISSUE TITLE
Conflicts with Bootstrap js plugin

### ISSUE THREAD

**Issue by micheleangioni** [yuche/vue-strap#18]
Hi,
It seems that at the moment VueStrap is not compatible with some Bootstrap javascript components.
I know that VueStrap is thought to replace the Bootstrap javascript components, but it would be nice that the two .js files could coexist peacefully.

As an example, let's take the tab plugin. This is a working example with Bootstrap 3.3.5. : https://jsfiddle.net/qy928t5f/

The same, **identical**, example with VueStrap as an external resorce is here: https://jsfiddle.net/4b06dee5/1/ . The behaviour is buggy.

Could you fix it?

Thanks

**Comment by yuche** [comment]
https://jsfiddle.net/4b06dee5/2/



在 2015年10月13日 下午5:52:45, Michele Angioni (notifications@github.com) 写到:

**Comment by yuche** [comment]
https://jsfiddle.net/4b06dee5/2/

**Comment by micheleangioni** [comment]
Yeah I know VueStrap has a Tab component which works fine.
The point imho is to keep VueStrap and Bootstrap js plugins fully compatiple each other.

**Comment by yuche** [comment]
My bad.

It's a bug. I'm working on it.

**Comment by yuche** [comment]
v0.1.2 fixed this bug.
https://jsfiddle.net/4b06dee5/3/

**Comment by micheleangioni** [comment]
Great @yuche ! :)
Keep up the good work!
