### ISSUE TITLE
More control over modal contents and issues with inline-template

### ISSUE THREAD

**Issue by andrewdavidcostello** [yuche/vue-strap#19]
I have posted it on the laracasts forum post here for reference:

https://laracasts.com/discuss/channels/general-discussion/vuestrap-bootstrap-components-built-with-pure-vuejs?page=3#reply-106358

Essentially would be great to have multiple insertion points or full support for inline-template.

When I used inline-template it only left some of my template intact and tried to replace/remove other items.

**Comment by yuche** [comment]
See new modal components with custom template. http://yuche.github.io/vue-strap/#modal

**Comment by andrewdavidcostello** [comment]
Thanks, just gave that a go however does it only support that specific structure as when I tried:

````
<modal show="{{@showPreview}}" effect="fade" width="800" v-el="emailPreview">
    <div class="modal-header {{ title | lowercase }}">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">{{ title }}</h4>
    </div>
    <div class="modal-header">
        <strong>Country:</strong> {{ country | uppercase }}
        <strong>Language:</strong> {{ language | uppercase }}
    </div>
    <div class="modal-body">
        <form>
            <div class="email-preview">
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Dismiss</button>
        <button type="button" class="btn btn-primary" v-on="click: triggerEvent">Confirm</button>
    </div>
</modal>
````

Everything was inserted into the modal body tag?

**Comment by chagamkamalakar** [comment]
@andrewdavidcostello   I have this error  Browserify Failed!: 'import' and 'export' may appear only with 'sourceType: module' . 
I did  window.VueStrap = require('vue-strap'); // i tried even full path also
new Vue ({
   components:{
    alert : VurStrap.alert;
})

what mistake I did ?

**Comment by yuche** [comment]
@chagamkamalakar 
Try:
```js
var alert = require('vue-strap/src/Alert.vue');
```

**Comment by chagamkamalakar** [comment]
Browserify Failed!: Parsing file /../../../node_modules/vue-strap/src/Alert.vue: 'import' and 'export' may appear only with 'sourceType: module' ..

**Comment by andrewdavidcostello** [comment]
@chagamkamalakar You are probably experiencing this issue?

https://github.com/yuche/vue-strap/issues/13

To get around this I use

````
window.VueStrap = require('vue-strap/dist/vue-strap.min.js');

components: {
        // Bootstrap
        'alert': VueStrap.alert,
        'datepicker': VueStrap.datepicker,
        'modal': VueStrap.modal,
        'panel': VueStrap.panel,
````

Not a nice solution but it works for now.

**Comment by chagamkamalakar** [comment]
@andrewdavidcostello 
 when i tried earlier .. it was complied with no error. but alert box is displayed like normal text .. i coded as bellow
----------------------------------------------

in main.js file      i did like
===========
window.VueStrap = require('vue-strap/dist/vue-strap.min.js');
-------------------------------- 
list.template.js
============
<div>
    <h2>Hotel listing</h2>
    <table class="table table-responsive table-bordered">
        <tr>
            <th>Name</th>
            <th>Latest Booked</th>
        </tr>
    </table>
    <button class="btn btn-default btn-lg"
            v-on="click:showRight = !showRight">
        Click to toggle alert on right
    </button>
    <alert
            show="{{@showRight}}"
            duration="3000"
            type="success"
            width="400px"
            placement="top-right"
            dismissable>
        <span class="icon-ok-circled alert-icon-float-left"></span>
        <strong>Well Done!</strong>
        <p>You successfully read this important alert message.</p>
    </alert>
</div>
----------------------------
list.js 
======
module.exports = {
    template: require('./list.template.html'),

    components: {
        'alert': VueStrap.alert 
    },

    data: function() {
        return {
            showRight: false,
            showTop: false
        }
    }
}
---------

It's not working, what it went wrong
