### ISSUE TITLE
pretty please for new release 1.0.9

### ISSUE THREAD

**Issue by vesper8** [yuche/vue-strap#192]
I really like your package.. and I can see it's super popular. But right now there's many problems with 1.0.8 being incompatible with new releases of other dependencies. I scratched my head for hours and finally I updated my package.json with this:

```
"dependencies": {
    ...
    "vue-strap": "git://github.com/yuche/vue-strap.git#master"
  }
```

And then it works :) But this is bad practice and could cause my application to break easily.

Here's to hoping you can release 1.0.9 soon!!

Many thanks for this great package

**Comment by amanpatel** [comment]
Because you used 'pretty please' in the subject, I just released this for you :-) Thanks for using the package!

**Comment by vesper8** [comment]
yes!!! you're awesome!! thanks!!!
