### ISSUE TITLE
官网示例select控件选中未保存值

### ISSUE THREAD

**Issue by Cacivy** [yuche/vue-strap#194]
http://yuche.github.io/vue-strap/#select

**Comment by amanpatel** [comment]
Please mention in English :-)

**Comment by Cacivy** [comment]
example select controls selected value is not saved

**Comment by MartanLV** [comment]
https://www.dropbox.com/s/sm94p1n1lcw4m7s/Screenshot%202016-05-14%2015.07.10.png?dl=0

at select component using vue/1.0.24 & vue-strap/1.0.9

this issue at *vue-strap/1.0.8* is not present

I used Chrome.

**Comment by amanpatel** [comment]
Fixed in 1.0.10. Thanks for reporting.
