### ISSUE TITLE
error coerceBoolean.js:3Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by Cacivy** [yuche/vue-strap#195]
webpack打包成功，但是只要使用某些组件报错
发现是因为引用的utils文件夹下的js报错，把`export default`改成module.exports=就可以了
请问是什么原因

**Comment by ChaoYuLeo** [comment]
我的改了也不能用，好奇怪。
![image](https://cloud.githubusercontent.com/assets/12207754/15453503/f409b93c-204a-11e6-94f7-148ff7593efa.png)

**Comment by Cacivy** [comment]
压缩确实不行，但是打包正常
推测是因为单独引用某个组件，组件依赖的js不会被babel语法转换

**Comment by ChaoYuLeo** [comment]
已经解决了，util中的所有js都改了才行的

**Comment by ChaoYuLeo** [comment]
虽然官方文档上有两种方式
import aside from 'vue-strap/src/aside'
import { aside } from 'vue-strap'
但是第一种方式始终是错误的，报错后虽然不影响运行，但是UglifyJs不会对JS进行压缩，导致文件很大。

**Comment by ChaoYuLeo** [comment]
试了一下，使用第二种方式引入后，不需要修改export default，打包压缩都正常了。

**Comment by yuche** [comment]
第一种方式错误的原因是因为 package.json 的 main file 现在指向打包过的 umd 文件

On May 22, 2016 at 10:44:40 PM, LeoYu (notifications@github.com) wrote:

试了一下，使用第二种方式引入后，不需要修改export default，打包压缩都正常了。

**Comment by Cacivy** [comment]
之前也比较过两种方式，但是因为引用多个组件，所以没深入测试。
明天试试

**Comment by Cacivy** [comment]
Unexpected token: name (alert) [./~/vue-strap/src/index.js:1,0]
我这改了还是不行，vue-strap/src/index.js没有转换

**Comment by Cacivy** [comment]
能给我贴一下你们的webpack配置吗，谢谢

**Comment by Cacivy** [comment]
解决了，改为用dist里面的vue-strap.js就行了。
因为修改了一些组件，还clone了项目重新打包替换。。
#199

**Comment by cgygd** [comment]
谢谢，改为module.exports=解决问题了。

**Comment by popo233** [comment]
In `webpack.base.conf.js`,
```
{
  test: /\.js$/,
  loader: 'babel',
  include: projectRoot,
  exclude: /node_modules/
}
```

Changing `/node_modules/` to `/node_modules(?!(.*vue-strap))/` will fix.
