### ISSUE TITLE
Any component that imports utils gives an error

### ISSUE THREAD

**Issue by ealves-pt** [yuche/vue-strap#203]
So I'm having several issues with components that import the anything inside `./utils`.

Running into trouble for the `radioBtn` and `Dropdown`. If I replace the import with the actual thing that is imported everything works like a charm.

Any idea what might cause this? I've just started a project using the latest `vue-cli`.

**Comment by amanpatel** [comment]
Can you try with v1.0.11 (just released)

**Comment by ealves-pt** [comment]
@amanpatel worked like a charm. Cheers!
