### ISSUE TITLE
Datepicker itemactive fail

### ISSUE THREAD

**Issue by lukpep** [yuche/vue-strap#206]
Datepicker component works but I get a lot of warnings:

> 
> build.js:9248 [Vue warn]: Error when evaluating expression "{'datepicker-dateRange-item-active':
> 			                    (this.mouthNames[this.parse(this.value).getMonth()]  === m) &&
> 			                    this.currDate.getFullYear() === this.parse(this.value).getFullYear()}": TypeError: Cannot read property 'getMonth' of null (found in component: <datepicker>)

I'm using 1.0.7 becouse 1.0.11 fails with v-select for me right now

**Comment by doonetheprune** [comment]
Have you got an example of how you are calling the datepicker

**Comment by lukpep** [comment]
`<datepicker>` in template is enough to cause those warnings
I thing it's something with marking the current day in datepicker calendar

**Comment by lukpep** [comment]
solved it.
warning was connected to fact that no date was picked in datepicker when it was oryginally created. I've injected date in ready state of component. After change to insert initial date in created state of component no warning are shown.
