### ISSUE TITLE
Allow Header Tag for Aside: {{ value }}

### ISSUE THREAD

**Issue by abrowne2** [yuche/vue-strap#224]
Hello,

Thank you for these components!
I was curious if there was a way to do something along these lines:

Say you have an aside component:
(from documentation):

```
<aside :show.sync="showRight" placement="right" header="Title" :width="350">

</aside>
```

Where header="Title", with the ability to do something like header="More Info: {{ value }}".

Currently, this is not possible.

**Comment by amanpatel** [comment]
Its possible, this is a vue related feature. When you use header="", it assumes what you have inside the quotes is a STRING.

If you use :header="", it assumes what you have inside is javascript code. So to get the effect you want, you need to use this:

```html
<aside :header="'More info: '+value">
</aside
```

**Comment by abrowne2** [comment]
I apologize for the unnecessary issue, I appreciate the assistance.

**Comment by amanpatel** [comment]
No problem. Glad I was able to help.

Aman
