### ISSUE TITLE
Incorrect component name - Sidebar - Aside (Documentation)

### ISSUE THREAD

**Issue by eduardostuart** [yuche/vue-strap#23]
```html
<aside show="true" placement="left" header="Title" width="300">
...
</aside>
```

![screen shot 2015-10-14 at 23 33 14](https://cloud.githubusercontent.com/assets/767879/10503425/0c398af0-72cc-11e5-9841-7bd8ef5a0124.png)

**Comment by mstnorris** [comment]
I'm unable to get the aside to work. Do you have an example you could give me. Thank you

**Comment by bflydesign** [comment]
Same issue here. I tried the modal successfully but the aside is not working at all.

I always get this error in my console: Uncaught SyntaxError: Unexpected token < on Aside.vue:1 
When I inspect my element in the DOM the aside-element is correctly build

**Comment by amanpatel** [comment]
@eduardostuart Hopefully you've figured this one out by yourself. In Vue you can name your components whatever you want. In this case, the import statement would read something like this:

```js
  import sidebar from 'src/Aside.vue'

// later in your component:

    components: {
      sidebar  // this makes <sidebar> available to be used in your template.
    },

```

Feel free to comment or re-open if this doesn't address the issue.
