### ISSUE TITLE
Documentation issue about radio-group

### ISSUE THREAD

**Issue by kpihus** [yuche/vue-strap#248]
Seems that documentation is bit wrong about radio-group

Correct syntax seems to be:
`                <radio-group :value.sync="chartType" type="primary">
                  <radio-btn value="left" checked>Left</radio-btn>
                  <radio-btn value="right" checked>Right</radio-btn>
                </radio-group>`
According to code, seems that it nees buttons to be <radion-btn> elements, not <radio>

Is there any point for me to update doc and create pull request.
Or those pull request wont be merged anyway ?

**Comment by lunardog** [comment]
Do you mean it should be `<radio-btn>` instead of `<radio>`?

**Comment by kpihus** [comment]
Yes, you are right, my bad.
