### ISSUE TITLE
Modal always adds padding to body

### ISSUE THREAD

**Issue by Lidbetter** [yuche/vue-strap#25]
When opening a modal when the window has no scroll bar, padding is still added to the body - this causes the content of the window to the left.

// no scrollbar
![screen shot 2015-10-23 at 12 35 59](https://cloud.githubusercontent.com/assets/6525616/10699139/bc0ad83c-7982-11e5-9218-f40afb8489cb.png)

// still adds padding
![screen shot 2015-10-23 at 12 35 09](https://cloud.githubusercontent.com/assets/6525616/10699150/ce7da148-7982-11e5-8c72-4f8c121b96b8.png)

**Comment by Morgul** [comment]
I think that the problem is [here](https://github.com/yuche/vue-strap/blob/master/src/utils/getScrollBarWidth.js#L20). I've found [several implementations](http://stackoverflow.com/a/13382873/480970) of this logic, and none of them seem to include this bit.
