### ISSUE TITLE
Timepicker?

### ISSUE THREAD

**Issue by gabrielkoerich** [yuche/vue-strap#26]
Hey!

First of all, awesome library. I would like to know if a timepicker would be out of scope. Really need it.

Thanks!

**Comment by yuche** [comment]
hen Vue.js v1.0 stable is released.
use this for now (require moment.js) . https://github.com/Haixing-Hu/vue-datetime-picker

**Comment by gabrielkoerich** [comment]
Cool! Thanks.

**Comment by amanpatel** [comment]
The vue-datetime-picker is excellent, but it is very heavy on the dependencies (requires jquery, font awesome, a 100kb datetimpicker widget, i18n, etc). I've committed a native (no dependency) version of it that allows very simple time picking. This is only under the bootstrap4 branch right now. Could be brought over the master branch without a lot of works.

**Comment by ablipan** [comment]
So we have date-picker and time-picker right now, would you add a datetime-picker @amanpatel

**Comment by amanpatel** [comment]
Definitely possible. Just don't have time for it right now :(. I can see it basically adopting the entire featureset of the vue-datetime-picker (which is still on Vue 0.12.x, and they have a lot of deps).

**Comment by smartpierre** [comment]
So the portability to bootstrap 3 will not be done ? :(

**Comment by amanpatel** [comment]
I'll work on this, just have been very busy. I don't think it will be too
much to port it back to the v1 branch. Thanks for the feedback.

**Comment by smartpierre** [comment]
Thank you ! I'll keep an eye on it :)
