### ISSUE TITLE
Aside - Uncaught SyntaxError: Unexpected token < on Aside.vue:1

### ISSUE THREAD

**Issue by bflydesign** [yuche/vue-strap#27]
I tried the modal successfully but the aside is not working.

When I inspect my element in the DOM the aside-element is correctly build but I always get this error in my console: Uncaught SyntaxError: Unexpected token < on Aside.vue:1

**Comment by bflydesign** [comment]
May it sounds logically but the button needs to be in the same vue-element as the aside. Is that right?

**Comment by yuche** [comment]
See https://github.com/yuche/vue-strap/blob/master/docs/example/asideDocs.vue

**Comment by bflydesign** [comment]
That was what I started from:

    <div id="leftMenu">
        <button class="hamburger" v-on="click:showLeft=true">
            <span class="fa fa-reorder fa-2x"></span>
        </button>

        <aside show="@{{@showLeft}}" placement="left" header="Title" width="350">
                    CONTENT HERE
        </aside>
    </div>

    <script src="{{ asset('/node_modules/vue/dist/vue.min.js') }}"></script>
    <script src="{{ asset('/node_modules/vue-strap/dist/vue-strap.min.js') }}"></script>
    <script src="{{ asset('/node_modules/vue-strap/src/Aside.vue') }}"></script>
    <script>
        var aside = VueStrap.aside;
	new Vue({
	    el: '#leftMenu',
		components: {
			'aside': aside
		},
		data: {
			showLeft: false
		}
	});
    </script>

**Comment by bflydesign** [comment]
Ok, appearantely I do not need to include the vue-component (Aside.vue in this example)
