### ISSUE TITLE
Browserify Failed!: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by FerchoCarcho** [yuche/vue-strap#28]
Hello,
I have tried
https://github.com/yuche/vue-strap/issues/19#issuecomment-147896277
but it doesn't fix the problem.
my app.js is

```
window.Vue = require('vue');
var resource = require('vue-resource');
window.Vuestrap = require('vue-strap/src/Alert.vue');
Vue.use(resource);
```
@yuche what is the solution?

**Comment by FerchoCarcho** [comment]
```
var Vue = require('vue');
var resource = require('vue-resource');
var Vuestrap = require('vue-strap/dist/vue-strap.min.js');
Vue.use(resource);
```
it worked like that

**Comment by prog-rajkamal** [comment]
**I have traced its actual cause** and will upload the fix in PR soon. meanwhile. Can anyone tell me how to open this issue and test my local code?
