### ISSUE TITLE
Someone who did the Afflix work?

### ISSUE THREAD

**Issue by marceloch2** [yuche/vue-strap#285]
Hello friends, 

Tried several different ways and markups to make affix work, also using the html from the docs and no luck.

Have somebody hear already worked with vue-strap affix?

Best, 

Marcelo.

**Comment by YuiZhou** [comment]
I suck by the same problem. There is no error for build and terminal. But its not working. The list has no style.

**Comment by wffranco** [comment]
The Affix component work as in the original in [bootstrap](http://getbootstrap.com/javascript/#affix):

>  ...you must provide CSS for the positioning and width of your affixed content.

> You must provide the styles, with the exception of `position: fixed;` on `.affix`, for these classes yourself (independent of this plugin) to handle the actual positions.

So the affix just give you the functionality for being or not fixed. The styles must be provided by you.
