### ISSUE TITLE
v-select: how to fire an event when option selected?

### ISSUE THREAD

**Issue by freeflyhm** [yuche/vue-strap#291]
```html
<v-select :value.sync="months">
          <v-option v-for="item of monthoptions" :value="item" @click="gotoMonth(item)">{{item}}</v-option>
</v-select>
```

@click is not working...

**Comment by wffranco** [comment]
in your code add a watcher to the value

```javascript
watch: {
  month: function (newVal) {
    this.gotoMonth(newVal);
  }
}
```

**Comment by freeflyhm** [comment]
thanks!

**Comment by songhlc** [comment]
@wffranco 
`
<v-select :value.sync="months" :value="period.item">
</v-select>
`

how can i fire events while select change with binding value like "period.item".

**Comment by wffranco** [comment]
@songhlc you check the documentation?
the v-select fires 2 events when change
```html
<v-select @change="changedValue" @selected="changedLabel"></v-select>
```
in your script you can handle the values
```javascript
methods: {
  changedValue: function(value) {
    //receive the value selected (return an array if is multiple)
  },
  changedLabel: function(label) {
    //receive the label of the value selected (the label shown in the select, or an empty string)
  }
}
```

**Comment by songhlc** [comment]
@wffranco 
```
<v-select @change='change' @select='select' :options.sync="giftoptions" justified search required close-on-select  :value.sync="gift_id"></v-select>

methods:{
    change () {
    },
    select() {
    }
}
```
no demo code only api description found in the document .
and it does not fire change method after i use @change.(select method is fine).
later i will give a demo page to reproduce problem.

**Comment by songhlc** [comment]
@wffranco it's weird！can't reproduce problem in my demo page.but still has bug in my project.thanks for answer my question. i will contact u later as soon as i reproduct the problem.

**Comment by wffranco** [comment]
you're using an older version of vue-strap, update to the last, because i workend on it alone for a time and had a lot of bugs in the way :v
