### ISSUE TITLE
TabSet,Tab demo is not working in latest code

### ISSUE THREAD

**Issue by wahyd4** [yuche/vue-strap#294]
I have come code like
``` javascript
import {Tagset} from 'vue-strap'
...
export default {
    components: {
      Tags: TagSet
    },
  }

```
The page says custom tag <tags> is not defined when I try to run it.

**Comment by wffranco** [comment]
Maybe because is misspelled?

1. in your example you wrote 'tag', must be 'tab'
2. I'm not implementing it using ES6, but I'm pretty sure that tabset should be in lowercase. Maybe should be changed for 'tabs' (simplified) or 'tabSet' (matching camelCase).

Greeting.

**Comment by wahyd4** [comment]
Ignore the typo.
After I change Tabset to tabset when doing the impor thing, it works.
But I am still confused why this should be lowercase rather than camel case( The file naming styling)?

**Comment by wffranco** [comment]
First of all: It was in lowercase before I start to touch the code.
Second: I suppose the intention is use it as `<tabset></tabset>`, if you use camel case then should be used as `<tab-set></tab-set>`... vue transform camelCase to kebab.
Anyway, in the end when you import it in your code you can rename it in your component list an use it as you wanted. I use to call it just `tabs`, then as in the documentation just use `<tabs></tabs>`.

Greeting.

**Comment by wahyd4** [comment]
👍
