### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by mstnorris** [yuche/vue-strap#30]
Please can you provide code examples to each of the elements with how to use them. I cannot get the aside to work.

**Comment by bflydesign** [comment]
There is some nice documentation in /docs/example/AsideDocs.vue

I used this:

	<script src="{{ asset('/js/vue/dist/vue.min.js') }}"></script>
	<script src="{{ asset('/js/vue-strap/dist/vue-strap.min.js') }}"></script>
	<script>
		var aside = VueStrap.aside;
		new Vue({
			el: '#leftMenu', // id of the containing div
			components: {
				'aside': aside
			},
			data: {
				showLeft: false
			}
		});
	</script>

**Comment by mstnorris** [comment]
Thank you but I am still unable to get it working. With the code you provided (I'm using a CDN for quickness) I get "_checkStatementvue.min.js:8:4321TypeError: undefined is not an object (evaluating 'a.parse(t).get')"

**Comment by stefanosandes** [comment]
Which version of vue that you are using ?

**Comment by mstnorris** [comment]
I'm using the latest version 1.0.3 (previously I was using 0.12.6). By the looks of the latest issue opened, I assume it doesn't support version 1.0 yet.

**Comment by amanpatel** [comment]
Looks like this issue has been addressed. If you have more questions feel free to open a new issue or comment.
