### ISSUE TITLE
Trigger v-on:focus of bs-input? 

### ISSUE THREAD

**Issue by metamet** [yuche/vue-strap#304]
Applying v-on:focus to a bs-input component doesn't work because (I assume) the parent element is a div with the class of form-group. 

Is there a workaround to allow for a the following code to be valid for the input inside the bs-input component?

` <bs-input label="Input Field" v-on:focus="setFocus"></bs-input> `

**Comment by wffranco** [comment]
Effectively, this component contain all the bootstrap input element, a div that include the input, header and messages, and focus don't work in a div element.
I added onfocus attribute, check the last update (v1.1.2)

**Comment by metamet** [comment]
Thanks @wffranco, that helps a bunch. Could we also get an onblur attribute added as well? That would round off the functionality of that.

**Comment by metamet** [comment]
Ultimately, what I think would be helpful here would be to create a data attribute for bs-input called "isFocused" that is toggled to true onfocus and toggled to false onblur. 

This would easily allow for the toggling of form styles when a field is selected, such as though v-bind:class="{ 'focused': isFocused }". Toggling a "focused" class for the form-group div would be a great native feature of this component. 

(Which is what I am ultimately trying to do here while using the bs-input component--make it so that when the form is focused, the style and location of the label changes by adding a "focused" class alonside "form-group".)

**Comment by metamet** [comment]
I created a pull request, creating onblur and the focused attribute/state: https://github.com/yuche/vue-strap/pull/309
