### ISSUE TITLE
how to use input with a number value

### ISSUE THREAD

**Issue by songhlc** [yuche/vue-strap#307]
import input from 'vue-strap'
<v-input :value.sync="good.unitpaycount"
               label="count"
               error="count not null"
               placeholder="count"
               required
               icon>

but props value only accept string.
what can I do if the type of value is number?

**Comment by wffranco** [comment]
Fixed, now you can use numbers.

Greeting.

**Comment by songhlc** [comment]
@wffranco  please close the issue
