### ISSUE TITLE
Vue 1.0 support?

### ISSUE THREAD

**Issue by xKairu** [yuche/vue-strap#31]
Is there an ETA on 1.0 support?

**Comment by stefanosandes** [comment]
+ 1

**Comment by yuche** [comment]
Use [v1 migration](https://github.com/vuejs/vue/releases/tag/1.0.0-migration) for now.

I'm working on v1 support.

**Comment by furey** [comment]
@yuche Legend! o/*\o

**Comment by FerchoCarcho** [comment]
The following is happening with the v1 version, How should I use https://github.com/vuejs/vue/releases/tag/1.0.0-migration , 
 ```
"[Vue warn]: Invalid prop: type check failed for show="@{{modalName.showMod}}". Expected Boolean, got String." instance.js:12409:7
"[Vue warn]: Invalid prop: type check failed for width="400". Expected Number, got String." instance.js:12409:7
"[Vue warn]: Failed to resolve directive: class" instance.js:12409:7
"[Vue warn]: Failed to resolve directive: style"
```

**Comment by arcanedev-maroc** [comment]
@yuche You're the real MVP (Most Valuable Programmer) :+1:

**Comment by amanpatel** [comment]
Hey, Thanks for the migration note.

However, it'd be REALLY nice to know if there is any ETA (i.e. planned for december, or sprint 2016, or something like that).

Boostrap v4 is not important as it is not out of alpha yet. VueJS 1.0.0 however has been released and considered stable.

**Comment by xKairu** [comment]
I have it running on 1.0.0-migration, but I don't feel like it's okay to use in production with all the warnings in place. Would like to fully migrate to 1.0.x asap.

**Comment by FerchoCarcho** [comment]
@yuche are you goint to release the 1.0 Version?

**Comment by amanpatel** [comment]
One other reason I'd like to know if this is planned is that I've now started to use your components (individually) in my code (modifying them to be compliant with VueJs 1.0.0.

If you had a github branch or any public plans, it'd be nice if I could contribute this back.

**Comment by s4l1h** [comment]
+1

**Comment by ryanwinchester** [comment]
+1

and thanks for the nice package :)

**Comment by FBI23** [comment]
+1 <3 Vue ecosystem

**Comment by amanpatel** [comment]
All, As somwhat promised, I've started a fork of this project that will give you VueJS 1.0.0 compatibility. I'm hoping this will become a pull-request to the main repository soon, but in the mean time, feel free to use it.

CAVEAT: Only Aside and Datepicker are currently updated. I'm probably going to update the others soon.

https://github.com/amanpatel/vue-strap

**Comment by FerchoCarcho** [comment]
@amanpatel Thanks for the effort, I will check it now.

**Comment by yuche** [comment]
@amanpatel Can you send me a PR on branch `v1` please?

**Comment by amanpatel** [comment]
Thanks. I just submitted it. I also caught and fixed an issue with yearSelect method in datepicker for 1.0.0 today. I'm planning to tackle the following now:

- dropdown
- typeahead
- tab
- button

**Comment by amanpatel** [comment]
Added Tab and Tabset in the new PR.

thanks.

**Comment by amanpatel** [comment]
@yuche Another PR is ready for your review.

This one is massive. I've updated the docs to run on v1 (including any syntax updates necessary for users who wish to use the componetns under v1).

In addition, I ported Select/Option, and Tooltip components (ohh and Affix too).

**Comment by FBI23** [comment]
Great work @amanpatel  !

**Comment by ghprod** [comment]
@amanpatel wow .. thats a lot works!

great. Thanks :)

**Comment by amanpatel** [comment]
This is now released, so closing this ticket. Any issues should be reported separately.
