### ISSUE TITLE
Select with Options doesn't show value

### ISSUE THREAD

**Issue by dansullivan86** [yuche/vue-strap#337]
When using Select with options the selected value isn't displayed.  

This can be seen in the docs:
https://yuche.github.io/vue-strap/#select

**Comment by m-behr** [comment]
#339 for proper function the given array needs label,value keys

**Comment by dansullivan86** [comment]
I'm trying to use it without passing an array of options, but using the v-option component method instead.  I need to do it this way so I can access the slot in v-option

**Comment by wffranco** [comment]
I don't noticed that bug, I will check it later.

**Comment by dyzz** [comment]
the value doesn't show up with webpack-dev-server, but works with production build

**Comment by wffranco** [comment]
Fixed but not uploaded yet, I am fixing another bug.
Maybe tonight or tomorrow is ready.

Greeting.

**Comment by wffranco** [comment]
Done.

**Comment by dansullivan86** [comment]
@wffranco Thanks for the quick fix on this, it now seems to be escaping slot contents though.

**Comment by wffranco** [comment]
Now the option component only fill the options from the parent select, and remove the element from the slot.
But I added support to html labels, so if you see some scape maybe must be the way you are filling the option text.

**Comment by dansullivan86** [comment]
@wffranco Definitely no escaping going on my end
`<v-option value="Alpha"><i class="fa fa-sort-alpha-asc"></i> {{ $t('Alphabetical') }}</v-option>`
