### ISSUE TITLE
tab-content not showing

### ISSUE THREAD

**Issue by schorsch3000** [yuche/vue-strap#34]
Hi,
i'm not sure if my issue is in fact a vue-strap issue, but i think you can tell me.
i have a quite simple setup using tabs in this [gist](https://gist.github.com/schorsch3000/57a703cda68ed02949f4).
Everything works perfect, except: the content of the active tab is not showing.
the the active div[role=tabpanel] has .tab-pane.fadein-transition
the inactive has .tab-pane.fadein-transition.hide, 
but there is a style:
.tab-content > .tab-pane{ display:none; }

i can easily just delete or overwrite this rule, but that seems strange to me.

even your [demo-page](http://yuche.github.io/vue-strap/#tabs) has this bug :)

is that some quirk in boot-strap or is this a vue-strap bug?

Thanks, Schorsch

**Comment by yuche** [comment]
Fixed

**Comment by Lluvio** [comment]
i suggest add the to here

> http://yuche.github.io/vue-strap/#tabs

because you have change the field `tabs` to `tabset`
