### ISSUE TITLE
About translations

### ISSUE THREAD

**Issue by smartpierre** [yuche/vue-strap#362]
Hello,

I use vue-strap on my projects and I need the **french** translations, however I don't understand how I am supposed to add it here : 

https://github.com/yuche/vue-strap/blob/master/src/utils/utils.js#L83

Could explain me how I should proceed or add this translation yourself please ?

````
/* fr */
let text = {
	daysOfWeek: ['Di', 'Lu', 'Ma', 'Me', 'Je', 'Ve', 'Sa'],
	limit: 'Limite atteinte ({{limit}} objets max).',
	loading: 'Chargement...',
	minLength: 'Taille Min.',
	months: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
	notSelected: 'Pas de sélection',
	required: 'Requis',
	search: 'Recherche'
}
````

Thanks !

**Comment by smartpierre** [comment]
@wffranco

**Comment by jokagent** [comment]
I managed to do it without hacking project files. Clone file dist/vue-strap-lang.js somewhere in your project,  add your translation (or, in your case, replace) into object inside VueStrapLang function. Then require your file before any import from vue-strap.
```
require('./VueStrapLang.js');
import {datepicker} from 'vue-strap';
```
Does anyone know, is this a right way to do it?

**Comment by wffranco** [comment]
Translations now is separated from the main vuestrap, so if you need translations you have to add the lang file.
Required:
´´´javascript
require('vue-strap/dist/vue-strap-lang.js')
´´´
or in your project include the file as in the documentation (is in 'getting started').

**Comment by smartpierre** [comment]
It worked !

Thanks :)
