### ISSUE TITLE
Modal close callback

### ISSUE THREAD

**Issue by happyDemon** [yuche/vue-strap#37]
I was browsing through the code and it seems the close callback is hardcoded(by just setting this.show to false).

It would be nice to actually define a close callback, where we for example could do some model cleanup when closing the modal (through the close button or by clicking the background).

I might be missing something though, I'm still new to VueJS

**Comment by yuche** [comment]
v1.0.2 fixed this issue.

**Comment by davestewart** [comment]
Hello. What's the callback? It doesn't seem to be documented.
