### ISSUE TITLE
checkbox-gupe do not update 

### ISSUE THREAD

**Issue by man032** [yuche/vue-strap#38]
Hello i have the following HTML code	

		
`<div class="col-lg-2" id="checkbox">`
  `<checkbox-group value="{{checkboxValue}}" type="default">`
 `<checkbox value="sucessful">Sucessful</checkbox>`
  `<checkbox value="failed" >Failed</checkbox>`
 `</checkbox-group>`
`<p>{{checkboxValue | json}}</p>`
`</div>`

And the following JS code

`var ch = new Vue({`
	  `components: {`
		  `'checkbox-group' : VueStrap.checkboxGroup,`
		  `'checkbox' : VueStrap.checkboxBtn`

	 },
	  el: '#checkbox',

	  data: function(){
	 	return {checkboxValue: []}
	  }

	  
	});

i can see the graphics works but the value dont get updated when clicking

Cpuld you help me please

**Comment by xKairu** [comment]
I'm just now getting the same thing with radio-group. I have my value synced with the binding and it simply doesn't update, even though the active state of each button does.

```
<radio-group :value.sync="selectedPlatform" type="default">
    <radio-btn @click="getEvents" v-for="platform in platforms" :value="platform.id.toString()">{{ platform.friendly }}</radio>
</radio-group>

{{ selectedPlatform | json }}
```

The output of `selectedPlatform` never changes from its default value.
