### ISSUE TITLE
Object doesn't support property or method 'onHit' [typeahead]

### ISSUE THREAD

**Issue by man032** [yuche/vue-strap#39]
Hello i have the following html code 
`<div class="col-lg-2" id="typeahead">`
 `<typeahead data="{{list}}" placeholder="Check Name" on-hit="{{slect}}">> </typeahead>`
`<p>{{item}}</p>`
`</div>`

and the followign js code

 new Vue({
  components: {
	  'typeahead':  VueStrap.typeahead,

  },
  el: '#typeahead',
  data: {
	  list: ['Name1', 'Name2', 'Name3'],
	  item: ''
  },

  methods: {
    select: function (item, targetMV) {
        this.$set('item', item);
    }
  }
});

i get the following error en IE 11
Object doesn't support property or method 'onHit'

and the followign error on Chrome

Uncaught TypeError: this.onHit is not a functions.methods.hit @ vue-strap.min.js:2(anonymous function) @ vue.min.js:6handler @ vue.min.js:7

**Comment by yuche** [comment]
Can you please put it on jsfiddle?
