### ISSUE TITLE
Are there some kind of documents of utils/NodeList.js?

### ISSUE THREAD

**Issue by psychomotor** [yuche/vue-strap#402]
I'm actually using NodeList.js to write some components that need DOM interactive, but i can't find this repo on github, so i'm wondering if this utility is wrote by someone in this repo? Thanks.

**Comment by wffranco** [comment]
NodeList was edited by me, but is based on that: https://github.com/eorroe/NodeList.js
The original nodelist have not event handlers, but the rest are close enought.
