### ISSUE TITLE
Modal Closing Unexpectedly

### ISSUE THREAD

**Issue by nacr** [yuche/vue-strap#425]
I have just realized that modals close unexpectedly although show is set to true.

Does any one verified this in the past?

Tks.

**Comment by nacr** [comment]
I can confirm that this is happening in "vue-strap": "^1.1.32" but not in "vue-strap": "^1.1.29".

**Comment by ipa1981** [comment]
Confirming:
:show.sync="open"

set open to true - opens modal, with display:block
set open to false - closes modal, with display: none
set open to true again - modal doesn't open, display: none remains

**Comment by ToxicTree** [comment]
We also had this problem.
Updated to 1.1.36 fixed the modal.
