### ISSUE TITLE
TypeError: Cannot read property 'collapse' of undefined

### ISSUE THREAD

**Issue by vinjegaard** [yuche/vue-strap#430]
I get these errors:

```[Vue warn]: Error when rendering component <navbar>: ```

```TypeError: Cannot read property 'collapse' of undefined```

when importing Navbar.vue like this:

```
<template>
  <navbar :placement="placement" :type="type">
    <a href="/" title="Home" slot="brand" class="navbar-brand">VueStrap</a>
  </navbar>
</template>

<script>

var VueStrap = require('vue-strap/dist/vue-strap.min.js')
var navbar = VueStrap.navbar

export default {
  components: {
    navbar
  },
  data () {
    return {
      placement : 'top',
      type : 'default'
    }
  },
  methods: {}

}
</script>
```
package.json dependensies:
```
"dependencies": {
    "bootstrap": "^3.3.7",
    "vue": "^2.1.0",
    "vue-loader": "^10.0.2",
    "vue-router": "^2.1.1",
    "vue-strap": "^1.1.34",
    "vuex": "^2.0.0",
    "vuex-router-sync": "^3.0.0"
  },
```

**Comment by redwards1966** [comment]
@vinjegaard I'm having this same issue too, did you solve it? I didn't see any comments on the fix.

**Comment by vinjegaard** [comment]
Hi @redwards1966! I closed this issue because the documentation doesn't say that this package is compatible with Vue 2, I assume you are also using Vue 2.1?

**Comment by redwards1966** [comment]
Yes, I'm using Vue 2.1 as well, darn. What did you end up using? I was just looking at bootstrap-vue because it supports Bootstrap 4.

**Comment by vinjegaard** [comment]
I ended up using https://bootstrap-vue.github.io/ @redwards1966, it works very well!
