### ISSUE TITLE
using vue-strap with cdn

### ISSUE THREAD

**Issue by qualisign** [yuche/vue-strap#433]
Hi, I'm a new user trying to do this with just a cdn.  It looks like I'm missing something, but I'm following the documentation as far as I can tell.

The accordian example here doesn't work... how do I fix it?  I've included all necessary sources.
https://jsfiddle.net/501m9a4y/1/

**Comment by wffranco** [comment]
1. youre using vue 2 with vue-strap 1.
2. vue-strap was done for bootstrap 3, not for bootstrap 4.
3. you have not set any vue instance.
4. you're using elements that don't correspond to vue-strap, maybe you're using is bootstrap-vue: https://github.com/bootstrap-vue/bootstrap-vue
