### ISSUE TITLE
function toggleClass

### ISSUE THREAD

**Issue by f0rb** [yuche/vue-strap#442]
I'm wondering why you use 'el.className = list;' instead of 'el.className = list.join(' ');' in function toggleClass, the previous code gives you a comma-separate class, eg. class="modal,fade,in", in Chrome and it leads the modal div displays incorrectly.
Hope to fix it ASAP.

**Comment by wffranco** [comment]
that was a little error.
fixed

**Comment by f0rb** [comment]
Yeah, it works now, many thanks~
