### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by appdrops** [yuche/vue-strap#452]
I'm not sure what classList refers to but I couldn't get it to work. I ended up removing the if statement below and it worked fine.

daySelect (date, el) {
      if (el.$el.classList[0] === 'datepicker-item-disable') {
        return false
      } else {
        this.currDate = date
        this.value = this.stringify(this.currDate)
        this.displayDayView = false
      }
    },

**Comment by Tyree** [comment]
I'm having the same problem. I was hoping to get some help on it. Oh well...

**Comment by thibz-16pixels** [comment]
So I hotfixed this bug on my machine :
Datepicker.vue - line22, fix event handling :
        `    <span v-for="d in dateRange" :class="d.sclass" @click="daySelect(d.date,$event)">{{d.text}}</span>
`
Datepicker.vue - line 188, access element classlist properly :
`if (el.target.classList[0] === 'datepicker-item-disable') {`

There's still a warning because props are mutated directly but it works. I have to move on but i'll try to fix the warning too. Then maybe do a commit here.

**Comment by Tyree** [comment]
Thanks, @Thibzzz!

**Comment by NewbMiao** [comment]
still have this problem,and report warn 
```
Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"
```

**Comment by Thibzzz** [comment]
Yeah two way binding is essentially dead on Vue2 with .sync deprecation (which this component relies on). So any component relying on .sync in Vue 2.0 + is now compromised. I fixed the problem locally by adding an external variable as a props and removed .sync all together. I suggest you do the same. Bluntly resumed : Vuejs's new philosophy is one way binding only so this won't work anymore. I have no time atm to make a commit with clean code here.

**Comment by PavloAndriiesh** [comment]
Hi guys. Is there any information about fixing this issue?

**Comment by AgniusSteponavicius** [comment]
I have same problem so far.

**Comment by codexp** [comment]
me too and it seems like it's an old bug that is still open
