### ISSUE TITLE
执行npm run build报错，有好心人帮忙看看哦

### ISSUE THREAD

**Issue by ysjun** [yuche/vue-strap#483]
ERROR in static/js/8.ecd8cb3bc9c56331d4a1.js from UglifyJs
SyntaxError: Unexpected token: keyword (const) [./~/vue-strap/src/utils/utils.js:2,0]

**Comment by shaoxiong789** [comment]
压缩混淆的时候报错，原因可能是你的项目不支持es6，而项目里面引用到相关组件，组件使用了这个js，这个js中有es6语法。建议你把项目再配置下
