### ISSUE TITLE
which vue-strap should we use now ?

### ISSUE THREAD

**Issue by vesper8** [yuche/vue-strap#507]
So.. I'm sure this is confusing a lot of other people as well.. I started using vue-strap well over a year ago.. and it seemed like this package was dead so I like many others started using https://github.com/wffranco/vue-strap instead. And more specifically I am using a specific commit because it just works and I'm afraid to break things.

I would like to get back to using "the latest" version. But I'm unsure which one to use! I'm on vue 2.x

Which is the latest / most stable / most actively developed ?

Is it https://github.com/wffranco/vue-strap or is it https://github.com/yuche/vue-strap/tree/v2 ?

**Comment by Luddinus** [comment]
+1

**Comment by SalemCode8** [comment]
if you drap down in this page 
https://github.com/yuche/vue-strap/tree/v2

and click the Documentation Link  this will take you to :

https://wffranco.github.io/vue-strap/

so they are both the same one so use this command to install the package :


npm install github:wffranco/vue-strap --save

**Comment by SalemCode8** [comment]
and if navigate to : 
https://github.com/wffranco/vue-strap

you will see it's forked from : 

https://github.com/yuche/vue-strap

**Comment by vesper8** [comment]
thank you mr obvious. i know one was forked from the other while the yuche one had become inactive

however they are not at all the same, if you look at the number of commits for both master branches and both v2 branches

For a while the wffranco was the fork to use because it was the most active by far, but then this original package became active and some things were merged in from wffranco, and as of this point.. some people continued using and developing the fork and some people went back to using the original

hence the question and confusion on which one to use now for those wanting the latest bug fixes

I personally have tried multiple times to come back to the original yuche branch and because of all the errors and breaking in my app I was forced to revert to a "stable" release from the wffranco

all in all though I am going to stop using vue-strap soon in lieu of something more organized and actively developed
