### ISSUE TITLE
#v1 dist js is not working properly

### ISSUE THREAD

**Issue by Hebilicious** [yuche/vue-strap#51]
Trying to use the https://github.com/yuche/vue-strap/blob/v1/dist/vue-strap.min.js
and '
```javascript
	components: {
		'datepicker': VueStrap.datepicker
	},
```

return this message: Unknown custom element: <datepicker> - did you register the component correctly?

trying to access VueStrap.datepicker from the console return undefined.
However VueStrap.default.datepicker is working, which is different from 0.12.
Is this intended?

**Comment by yuche** [comment]
It's not intended.
Thank you for notified. Should be fine now.
