### ISSUE TITLE
Dist JS not in sync with the lastest bugfixes

### ISSUE THREAD

**Issue by Hebilicious** [yuche/vue-strap#54]
The dist js has not been compiled since your latest bugfixes, so the CDN versions and the browser global versions are bugged, especially the modal components.

**Comment by amanpatel** [comment]
I just updated dist. @yuche Is a release/tag needed for the CDN versions to update? This would also fix #57

**Comment by yuche** [comment]
@amanpatel 
You can do whatever you think is necessary.

**Comment by amanpatel** [comment]
Just tagged a new 1.0.1 release. Closing this for now, give it a few minutes for CDNJS to update.

**Comment by amanpatel** [comment]
Re-opened. @yuche would you be able to npm publish this on your end? As you probably already know this will update the cdnjs copy and resolve a few modal issues.

Thanks.

**Comment by yuche** [comment]
@amanpatel 
Done.
