### ISSUE TITLE
Modal Content repeats 3 times? :O

### ISSUE THREAD

**Issue by FerchoCarcho** [yuche/vue-strap#57]
See for yourself, Inside the custom modal content the header, the body and the footer is being displayed 3 times, it is not my issue because the <modal> tag is okay, and the bug comes inside it.
http://postimg.org/image/7ag8m66ul/284680fb/
Using the v.1

**Comment by amanpatel** [comment]
A fiddle would be more helpful.

**Comment by FerchoCarcho** [comment]
okay @amanpatel  :smile:

**Comment by yuche** [comment]
I think #53 fixed the problem.

**Comment by FerchoCarcho** [comment]
Thank you @yuche !!!

**Comment by FerchoCarcho** [comment]
Sorry but it is  Not working even with changing to Slot and changing the Modal.vue at Src for the commits made by @Sunmile .
here is my modal 
```
 <modal  :show.sync="Modals.showModCrear" :width="400" title="modalTitle">
        <div slot="modal-body">BODY</div>
        <div slot="modal-footer" class="modal-footer">FOOTER</div>
    </modal>
```
im using

```
var Vuestrap = require ('vue-strap/dist/vue-strap.min.js');
```
because the 
```
var alert = require('vue-strap/src/alert');
// or
var alert = require('vue-strap').alert
```
not working. with
```
  "dependencies": {
    "babel-plugin-transform-runtime": "^6.1.18",
    "babel-preset-es2015": "^6.1.18",
    "babel-runtime": "^6.2.0",
    "bootstrap-sass": "^3.0.0",
    "laravel-elixir": "^3.0.0",
    "vue": "^1.0.10",
    "vue-hot-reload-api": "^1.2.1",
    "vue-resource": "^0.1.17",
    "vue-router": "^0.7.7",
    "vue-strap": "^1.0.0",
    "vueify": "^6.0.0",
    "vueify-insert-css": "^1.0.0"
  }
```

**Comment by amanpatel** [comment]
First thing I would suggest is to remove your node_modules and perform a fresh npm install. This will make sure you have the latest vue-strap.

The second problem I see is your modal code should be something like this:

```js
 <modal  :show.sync="Modals.showModCrear" :width="400" title="modalTitle">
        <div slot="modal-body" class="modal-body">BODY</div>
        <div slot="modal-footer" class="modal-footer">FOOTER</div>
    </modal>
```

Will update the docs shortly.

**Comment by FerchoCarcho** [comment]
@amanpatel  I made The changes you suggested me but only

```
  "vue-hot-reload-api": "^1.2.2",
```
updated, So I must assume my other components are okay.
Sadly I still get 3 Repeated content inside that Modal.
But I don't know if only my configuration is the one that fails, or is it the vue-strap itself which is failing.
Also, I have noticed  the modalTitle which has the value of 'test' is not passed to the Modal and it shows like 
http://postimg.org/image/d2rnzoptx/
because at thes src\Modal.Vue 
```
 <slot name="modal-header">
          <div class="modal-header">
            <button type="button" class="close" @click="close"><span>&times;</span></button>
            <h4 class="modal-title" >{{title}}</h4>
          </div>
</slot>
```
if no modal-header is provided , the modal should display the title with the X button to close the modal, but mine doesnt.

**Comment by amanpatel** [comment]
https://jsfiddle.net/fqdx8auL/

This recreates the problem using the CDN version. it looks like @yuche hasn't had a chance to update the CDN dist yet. I'll wait for him to do it.

**Comment by FerchoCarcho** [comment]
Thank you very much @amanpatel!!

**Comment by amanpatel** [comment]
CDN will update shortly. If you are using webpack, you should already have the latest copy. Closing this for now.

**Comment by FerchoCarcho** [comment]
Reggardin some bugs with the Modal, Im using it even its not working properly yet. So I had a problem uploading a File, let me tell you that the file wasnt being catched. Read the following thread about it.
http://forum.vuejs.org/topic/674/not-working-when-getting-the-value-of-an-input-file/11
