### ISSUE TITLE
vue-strap/src/main.js Line 1: Unexpected token

### ISSUE THREAD

**Issue by henjue** [yuche/vue-strap#60]
## file:a.vue
```vue
<template>
    <div class="view" transition>
      <h1>This is page B.</h1>
      <p>I'm... a bit less complicated.</p>
    </div>
    <alert/>
</template>
<script>
import {alert} from 'vue-strap'
export default{
    components:{
        alert
    }
}
</script>
]
```

## Error info
```
./~/vue-strap/src/main.js
Module parse failed: /Users/apple/Documents/codes/im-web-admin/node_modules/vue-strap/src/main.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| export {alert}  from './Alert.vue'
| export {carousel} from './Carousel.vue'
| export {slider} from './Slider.vue'
 @ ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/b.vue 7:16-36
```

**Comment by amanpatel** [comment]
What's your webpack config file? This error is telling you that you are not using the babel loader to compile vue-strap code.

**Comment by henjue** [comment]
@amanpatel 
```js
// webpack.config.js
var webpack = require('webpack')
var CommonsChunkPlugin = webpack.optimize.CommonsChunkPlugin
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var path = require("path");
module.exports = {
  cache: false,
  entry: {
      index:'./src/js/index.js',
      im:'./src/js/im.js'
  },
  output: {
    path: path.join(__dirname,'dist'),
    publicPath: "/dist/",
    filename: "[name].js"
  },
  plugins: [
    new CommonsChunkPlugin('vendor.js'),
    new ExtractTextPlugin('vendor.css')
  ],
  babel: {
    presets: ['es2015'],
    plugins: ['transform-runtime']
 },
  module: {
    loaders: [
      { test: /bootstrap\/js\//, loader: 'imports?jQuery=jquery' },
      { test: /\.(woff|woff2)$/,   loader: "url?limit=10000&minetype=application/font-woff" },
      { test: /\.ttf$/,    loader: "url?limit=10000&minetype=application/octet-stream" },
      { test: /\.eot$/,    loader: "file" },
      { test: /\.svg$/,    loader: "url?limit=10000&minetype=image/svg+xml" },
      {
      	test: /\.js$/,
        exclude: /node_modules|vue\/src|vue-router\/|vue-loader\/|vue-hot-reload-api\//,
      	loader: 'babel'
      },
      {test:/\.css$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader")},
      {test: /\.scss$/, loader: "style!css!sass"},
      {test: /\.less$/, loader: "style!css!less"},
      {test: /\.(png|jpg)$/,loader: 'url?limit=4096'}, // 图片低于 4MB 时转换成 inline base64，非常神奇！
      {test:/\.vue$/,loader:'vue'}
    ]
  }
}

```

**Comment by amanpatel** [comment]
Where did you get this line from?

```js
      {
        test: /\.js$/,
        exclude: /node_modules|vue\/src|vue-router\/|vue-loader\/|vue-hot-reload-api\//,
        loader: 'babel'
      },
```

The exclude should not contain "node_modules" (AFAIK). This is what causing the problem. I'd suggest removing or updating it as needed, something like below might work:

```        exclude: /vue\/src|vue-router\/|vue-loader\/|vue-hot-reload-api\//,```

**Comment by yuche** [comment]
@amanpatel 
He got it in [here](https://github.com/vuejs/vue-hackernews/blob/gh-pages/webpack.config.js#L21).

@henjue 
You can try require components in ES5 way. eg:
```
var alert = require('vue-strap/src/Alert');
```

**Comment by henjue** [comment]
@amanpatel Do not rule out node_modules, other modules will be reported to the wrong

@yuche I want to use the other modules, such as require ('path'); require ('vue');

**Comment by EricPMulligan** [comment]
@yuche: It mentions on [babel-loader's GitHub](https://github.com/babel/babel-loader#babel-loader-is-slow) to add `node_modules` to the exclude list since it may cause babel-loader to be very slow if the app has tons of dependencies. I was able to use `var VueStrap = require('vue-strap/dist/vue-strap');` which solved the webpack issue.

I would suggest pointing the main script in your `package.json` file to the `vue-strap/dist/vue-strap.js`.

**Comment by amanpatel** [comment]
@EricPMulligan Your suggested fix makes so much sense. So thanks for mentioning it here. By the way the correct value for ```main``` in ```package.json``` will be ```dist/vue-strap.js``` (its relative to the modules directory).

Since this might break user's import code, I'm going to wait until @yuche can chime in. But I'm all for this change. (BTW, I tried this on my fork, and it worked fine for my project, albeit, almost all my import statements broke because I was requiring individual components like so: ```import Typeahead from 'vue-strap/src/Typeahead.vue';``` had to change to ```import {typeahead as Typeahead} from 'vue-strap';```

**Comment by EricPMulligan** [comment]
@amanpatel: Awesome! :-)

**Comment by amanpatel** [comment]
Well. After a lot more testing with the new setting, I'm satisfied. I think the old require() code will continue to work since they are using relative path and specifying the src/ folder.

This has been pushed. I'm going to create a 1.0.3 version/tag. This also includes an update to the Select component which allows searching!

**Comment by EricPMulligan** [comment]
Awesome! Out of curiosity, has NPM been updated? It says that the latest version is [1.0.2](https://www.npmjs.com/package/vue-strap).

I'm unfamiliar with the process so my apologies if it's normal that it takes a few days for it to be updated.

**Comment by amanpatel** [comment]
@yuche Please do a npm publish when you get a chance.

**Comment by EricPMulligan** [comment]
1.0.3 now shows up on npmjs.org. I updated to 1.0.3 and I changed my require to `require('vue-strap')` and it worked! Thanks so much everyone!

**Comment by amanpatel** [comment]
Closing this.

**Comment by connor11528** [comment]
I am trying both the require and import syntax but get a similar error.

My code:

```
// import Carousel from 'vue-strap/src/Carousel.vue'
// import Slider from 'vue-strap/src/Slider.vue'
var Carousel = require('vue-strap/src/Carousel.vue');
var Slider = require('vue-strap/src/Slider.vue');
```

Error:

```
Hash: f74c06386dd5e663a202                                                    b Version: webpack 2.7.0
Time: 5114ms
                                             Asset     Size  Chunks                    Chunk Names
 violin1_back.jpg?59392fd277f63c7110a8aa419d7f4923  62.8 kB          [emitted]         
violin1_front.jpg?b3dcdd2112d9694ef3b3a95f75285f89    63 kB          [emitted]         
 violin1_head.jpg?5e99ab2f89c85ef20eef2fa268fb2d4f  59.3 kB          [emitted]         
                                          build.js   759 kB       0  [emitted]  [big]  main
                                      build.js.map   986 kB       0  [emitted]         main

ERROR in build.js from UglifyJs
Unexpected token: name (blurEvent) [./~/vue-strap/src/utils/NodeList.js:3,0][build.js:27291,4]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I am using the webpack-simple Vue.js starter template config file. Everything run in development. The above error happens when I try to build for deployment

**Comment by connor11528** [comment]
I commented out the Uglify section of my webpack config and everything worked:

```
    // new webpack.optimize.UglifyJsPlugin({
    //   sourceMap: true,
    //   compress: {
    //     warnings: false
    //   }
    // }),
```
