### ISSUE TITLE
need 'closable' for modal

### ISSUE THREAD

**Issue by ablipan** [yuche/vue-strap#62]
To disable/enable close modal by clicking on the dimmer

**Comment by yuche** [comment]
Will do tonight. (Timezone GMT +8)

**Comment by ablipan** [comment]
@yuche :+1:

**Comment by yuche** [comment]
Modal component now has a option named `backdrop`,which controls disable/enable close modal by clicking on the backdrop.

[More details](https://github.com/yuche/vue-strap/commit/e96a602f1772050d250081700e1f1855f884d97f).

**Comment by ablipan** [comment]
:100:
