### ISSUE TITLE
Can we add bootstrap-table component?

### ISSUE THREAD

**Issue by wenzhixin** [yuche/vue-strap#64]
I just begin to use `vue.js` and `vue-strap`, thanks for your work, they are excellent!
Do you think can we add [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) to `vue-strap` like `bootstrap-select`?

**Comment by amanpatel** [comment]
Take a look at this video: https://laracasts.com/series/learning-vuejs/episodes/6

A full featured grid component might make sense, but it might be too big of a widget to be contained within vue-strap. I think vue-strap should stick to smaller widget that make life easier for developers. The original goal of this project was to remove the need for bootstrap.js file and make bootstrap completely powered by vue.
