### ISSUE TITLE
fail to rebuild vue-strap

### ISSUE THREAD

**Issue by leinue** [yuche/vue-strap#67]
hello,im a Chinese,it looks like that the component 'app.vue' has a different language concerning the button 'confirm' and the button 'close'.i want to translate it to chinese,so i rebuild vue-strap,but npm reported an error,can you help me to handle it?thanks!
i use OS X

**run**
``` shell
npm run build
```
**then**

module.js:339
    throw err;
    ^

Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/private/var/www/poimoe/web/poi/node_modules/.bin/webpack:15:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! vue-strap@1.0.2 build: `webpack --progress --hide-modules --config  webpack.build.min.js && webpack --progress --hide-modules --config  webpack.build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-strap@1.0.2 build script 'webpack --progress --hide-modules --config  webpack.build.min.js && webpack --progress --hide-modules --config  webpack.build.js'.
npm ERR! This is most likely a problem with the vue-strap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --hide-modules --config  webpack.build.min.js && webpack --progress --hide-modules --config  webpack.build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls vue-strap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/www/poimoe/web/poi/node_modules/vue-strap/npm-debug.log

then i try to

``` shell
npm install optimist -g
npm install optimist --save-dev
```

the same

**Comment by amanpatel** [comment]
Try this:

1) remove folder ``node_modules`` .
2) run ``npm cache clean``
3) run ``npm install``

**Comment by amanpatel** [comment]
Closing this, please re-open or start a new issue in case it didn't work out.
