### ISSUE TITLE
 vue.common.js:967 [Vue warn]: Invalid prop: type check failed for show="{{@showModal}}". Expected Boolean, got String.

### ISSUE THREAD

**Issue by matisoffn** [yuche/vue-strap#68]
I copied the example from `http://yuche.github.io/vue-strap/` for the modal, and I'm getting multiple Vue warnings, and when clicking the button the modal doesn't appear.

Vue warnings:

```
[Vue warn]: Invalid prop: type check failed for show="{{@showModal}}". Expected Boolean, got String.
[Vue warn]: Invalid prop: type check failed for width="400". Expected Number, got String.
[Vue warn]: Invalid expression. Generated function body:  scope.click:scope.showModal=true
```

I'm just trying to use the default example for a modal, what's wrong here?

**Comment by matisoffn** [comment]
Found this fiddle https://jsfiddle.net/fqdx8auL/ on another issue, solved my problem.

**Comment by amanpatel** [comment]
This has been updated in the docs, it might be the case that @yuche hasn't updated or merged the githup pages site yet. Since I am not really familiar with gh-pages, I'll let him chime in and possibly update the docs.

**Comment by matisoffn** [comment]
@amanpatel just noticed that in the `/doc` dir.  Definitely should be updated in both spots, seeing as many people likely use the demos.

Thanks for your work guys.

**Comment by amanpatel** [comment]
@matisoffn Never used gh-pages before. I am sure yuche will have to grant me permission to his site. I've assinged this task to him.

**Comment by amanpatel** [comment]
@matisoffn  Just updated the gh-pages branch (took a bit of work for some reason it had conflicts since it was out of date for a while). In either case, the docs are updated!
