### ISSUE TITLE
Form select and checkbox documentation

### ISSUE THREAD

**Issue by nlassiter** [yuche/vue-strap#69]
Could you make the select and checkbox documentation more detailed. Specifically I'm trying to understand what attributes and values need to be provided to prefill these form elements, say if the form was already posted. When I tried to use `v-model`, I received a warning 'v-model doesn't support element DIV'

- The select sort of works for me, but the option value is being shown in the option labels in addition to the label. When the menu is collapsed, the values show instead of the labels.
- The checkbox is making an inverse selection for me.

See jsfiddle here:
http://jsfiddle.net/0Ltpdcj1/3/

**Comment by amanpatel** [comment]
Looks like you found a bug. I'll probably push a fix out soon. To be clear the select component is working fine, the checkbox is not (specifically: its not initializing to the original selected values).

**Comment by nlassiter** [comment]
1. In the select, when the values are selected, I expected to see "1st,2nd" rather than "1,2". Is that a bug?
2. Also in the select dropdown, see how the options show "1st 1" rather than just "1st". Is something wrong in my code?

**Comment by amanpatel** [comment]
Should be fixed. Will be included in 1.0.4 release soon.
