### ISSUE TITLE
Proposal: To change most parts in the documentation reference to the newer vue syntax

### ISSUE THREAD

**Issue by rajabishek** [yuche/vue-strap#71]
For example in the alert section http://yuche.github.io/vue-strap/#alert

The alert component takes in the show prop as show="{{@showTop}}"
But it must be v-bind:show.sync="showTop"

In the newer vue syntax we have to add the .sync modifier for 2 way data binding instead of @.
And for dynamic binding we have to v-bind:prop instead of prop = {{}}.

**Comment by amanpatel** [comment]
Fixed in 6042ec5 Will do a release soon.
