### ISSUE TITLE
Attributes are ignored on component because the component is a fragment instance

### ISSUE THREAD

**Issue by luis-conor** [yuche/vue-strap#72]
Hi,
I'm trying to use vue-strap in my project, which uses the Vuejs suggested large scale application ES6 (single-file) components.
I get errors like this one below - and the end result is that the vue-strap components don't work or render correctly.
```[Vue warn]: Attributes "type", "dismissable" are ignored on component <alert> because the component is a fragment instance: http://vuejs.org/guide/components.html#Fragment_Instance```
This is one example for the `alert` vue-strap component, but it's similar if I use other vue-strap components.

I thought I could be doing something wrong on my project so I tested on the Vuejs hacker news clone (https://github.com/vuejs/vue-hackernews) but I still get the same...
For reproducing, here is what I did:
```sh
git clone https://github.com/vuejs/vue-hackernews
cd vue-hackernews
npm install
npm run dev
#all working fine
```
then onto vue-strap install:
```sh 
npm install vue-strap
```
Change `index.html` to reference Boostrap CSS using `<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.css">`, and then in one of the app components `NewsView.vue` I tried to use them

```html
<script>
....
import alert from 'vue-strap'

export default {

  name: 'NewsView',

  components: {
    Item,
    sidebar,
    alert,
    modal
  },
...
</script>
```
and the `template` 
```html
<template>
<div>
 <alert :type="success" dismissable>
  <strong>Well Done!</strong>
  You successfully read this important alert message.
</alert>


  <div class="news-view" :class="{ loading: !items.length }">
    <!-- item list -->
    <item
      v-for="item in items"
      :item="item"
      :index="$index | formatItemIndex"
      track-by="id">
    </item>
    <!-- navigation -->
    <div class="nav" v-show="items.length > 0">
      <a v-if="page > 1" :href="'#/news/' + (page - 1)">&lt; prev</a>
      <a v-if="page < 4" :href="'#/news/' + (page + 1)">more...</a>
    </div>
  </div>
</div>
</template>
```

Any idea what I'm doing wrong - or is this an actual vuejs/vue-strap issue?
Thanks in advance!
L/C

**Comment by luis-conor** [comment]
Hi, any insight here would be awesome. 
Thanks!

**Comment by amanpatel** [comment]
```
 <alert :type="success" dismissable>
```

First, in the above code, make sure that "success" is a variable in your VM. If its not, its better to use the literal syntax:

```
 <alert type="success" dismissable>
```

This means that the string 'success' will be assigned.

I created a fiddle that tries to recreate your problem, but there are no warnings created (even with vue's debug mode on).

https://jsfiddle.net/amanpatel/Lzpcoe18/

**Comment by amanpatel** [comment]
Closing this until more information is provided.
