### ISSUE TITLE
Modal not working as per documentation

### ISSUE THREAD

**Issue by mrgodhani** [yuche/vue-strap#74]
Hi

As per documentation modal window isn't working.

**Comment by pedrofgsrj** [comment]
It seems the docs haven't been updated yet to work with the new vue syntax, as pointed out on issue #71

Check out [this fiddle](https://jsfiddle.net/fqdx8auL/ ) from issue #68 . It might help you while the docs are not updated.

**Comment by amanpatel** [comment]
Sorry, yuche probably needs to push a gh-pages update He's probably busy, there is a ticket assigned already, so I'm closing this.
