### ISSUE TITLE
[Feature] Datetimepicker

### ISSUE THREAD

**Issue by nivv** [yuche/vue-strap#8]
Hey! First of all, this looks promising :) 

It would be nice if the datepicker could be extended to allow time as well. Something like this plugin:
https://eonasdan.github.io/bootstrap-datetimepicker/

Localization would also be neat feature.

**Comment by yuche** [comment]
I was thinking maybe write a Timepicker component, like [this](https://angular-ui.github.io/bootstrap/#/timepicker). 

You can modify [weekRange](https://github.com/yuche/vue-strap/blob/master/src/Datepicker.vue#L97) and [mouthNames](https://github.com/yuche/vue-strap/blob/master/src/Datepicker.vue#L104) for localization.

**Comment by arcanedev-maroc** [comment]
:+1: for `angular-ui` timepicker.

**Comment by micheleangioni** [comment]
:+1: nice improvement!

**Comment by nivv** [comment]
@yuche So was this added or am I missing why you closed the issue? :smile:
