### ISSUE TITLE
What kinda of string is the datepicker expecting?

### ISSUE THREAD

**Issue by w0bbes** [yuche/vue-strap#85]
Hey guys,

Not sure what kind of string im suppose to put in for the datepicker, but i'm getting error for everything.

So I'm inputting this for the value: 01/08/2016
With this format: :format="MM/dd/yyyy"

Getting the following errors:

    Vue warn]: Error when evaluating expression "{'datepicker-dateRange-item-active': (this.mouthNames[this.parse(this.value).getMonth()]  === m) && this.currDate.getFullYear() === this.parse(this.value).getFullYear()}". 
    Uncaught TypeError: Cannot read property 'getMonth' of null

**Comment by amanpatel** [comment]
Try this http://jsfiddle.net/cds7ywh1/1/

You are using ":" in front of format. That's incorrect. Vue will try to evaluate "MM/dd/yyyy" which is not valid javascript (or not what you want it to do anyway).

Replace :format, with format="MM/dd/yyyy".

thanks,

**Comment by w0bbes** [comment]
Sorry, what I ment with :format="MM/dd/yyyy" is that I've actually put in "MM/dd/yyyy" as the format.

Im wondering about that kind of value I have to supply. Your example displays an empty value. What if I have a preset one? like :value="12-1-2016"... how would I handle this?

**Comment by amanpatel** [comment]
You specify format via format="...", and not :format="...".  My fiddle example displays an empty value because I didn't initialize it. See this one which defaults to 12/01/2012

http://jsfiddle.net/cds7ywh1/2/

**Comment by stefan-neuser** [comment]
Thanks for jsfiddle @amanpatel.

But unfortunately its not possible to init a vuestrap datepicker with an empty value. That drives my crazy at the moment becouse this widget is kind of useless without this possibility.

**Comment by aobowtd** [comment]
agree with @stefan-neuser, default value is unnecessary in most cases

**Comment by StefanNeuser** [comment]
Why this issue is closed?
