### ISSUE TITLE
Popovers/Tooltips display in the wrong place when a component is loaded via v-show

### ISSUE THREAD

**Issue by dojorob76** [yuche/vue-strap#86]
First of all, thanks for a great package! Unfortunately, I have run into the following issue: 

I have all of my VueStrap components loaded globally, and they all work fine on content that is already available (hardcoded) in a template. However, if a nested component is loaded via v-show or v-if and that component's template contains the popover or tooltip components, the popovers and tooltips display in random places on the page. What is the best way to deal with this issue?

Simplified Example:

'app.js'

```
var Vue = require('vue');
var VueStrap = require('vue-strap/dist/vue-strap.min.js');

var VPopover = Vue.extend(VueStrap.popover);
var VTooltip = Vue.extend(VueStrap.tooltip);
// etc., etc.

Vue.component('v-popover', VPopover);
Vue.component('v-tooltip', VTooltip);
// etc., etc.

import Authentication from './components/auth/authentication.vue'

new Vue({
    el: '#app',

    components: {
        Authentication
    }

});
```

'components/auth/authentication.vue'

```
import AppRegister from './register/app-register.vue'
import AppLogin from './login/app-login.vue'

export default {
    data () {
        return {
            showAppLogin: true,
            showAppRegister: false
        }
    },

    template: '#authentication-template',

    components: {
        'app-register': AppRegister,
        'app-login': AppLogin
    },

    methods: {
        appLoginWasClicked () {
            this.showAppRegister = false;
            this.showAppLogin = true;
        },
        appRegisterWasClicked () {
            this.showAppLogin = false;
            this.showAppRegister = true;
        }
    }
}
```

'register/app-register.vue'

```
export default {
    template: '#app-register-template'
}
```

'login/app-login.vue'

```
export default {
    template: '#app-login-template'
}
```

HTML

```
<div id="app">
    <!-- Anything hardcoded in here that uses any vue-strap component will work -->
    <!-- ---------------------------------------------------------------------- -->

    <authentication></authentication>

    <template id="authentication-template">
        <v-tooltip content="Example, WORKING TOOLTIP" placement="top">
            WORKING TOOLTIP
        </v-tooltip> <!-- This works fine. No Problems -->

        <app-login v-show="showAppLogin"></app-login>
        <app-register v-show="showAppRegister"></app-register>
    </template>

    <template id="app-login-template">
        <v-popover effect="scale" trigger="hover" placement="top" title="THIS WILL WORK" content="This will work, because 'showAppLogin' is set to true when the component loads">
            WORKING POPOVER
        </v-popover> <!-- This works properly because it is set to display initially -->
    </template>

    <template id="app-register-template">
        <v-popover effect="scale" trigger="hover" placement="top" title="THIS WILL NOT WORK" content="The popovers will now display in random places on the page, because this component is loaded later with v-show>
            POPOVER DISPLAYS INCORRECTLY
        </v-popover><!-- This popover will not display correctly unless I change "showAppRegister" to 'true' in the ($parent) Authentication component -->
    </template>

</div>
```

When loading jQuery under these circumstances, I could do something with `$nextTick` in the component's ready method to ensure that the script is available after the component has rendered. I assume there is some way to implement the same kind of logic with vue-strap, but I would prefer to find out what you consider 'best practices' in this scenario (or, if I'm just missing something super obvious - which is entirely possible!). 

Any help you can offer would be greatly appreciated. Thanks in advance!

**Comment by dojorob76** [comment]
Sorry, forgot the triggers...

In HTML:

    <button v-on:click="showAppRegister">Register</button> 
    <button v-on:click="showAppLogin">Login</button>

**Comment by dojorob76** [comment]
Just a quick update: I have tried this with modals and asides as well. They both produce the same result. If the HTML element that the popover or tooltip is connected to is hidden on page load, then the popovers/tooltips will not display correctly when the HTML element becomes visible. Any direction on this would be helpful. Thanks again!

**Comment by petercoles** [comment]
I'm seeing the same issue even when the tooltip or popover isn't controlled by v-show. In my case the problem may result from using them as child components.

**Comment by amanpatel** [comment]
I'm going to look at this soon. I've run in to something similar and will need to fix it soon anyway. My eta is sometime this Wednesday.

**Comment by drwebman** [comment]
Hi amanpatel did you ever get this problem solved? I have the same issue where popovers in a table display at the top-left of the table rather than over the button. I'm working on it too, but can't think of a solution !

**Comment by hannes-dahlberg** [comment]
Get the same thing. Displays in the wrong place when tooltip is placed in table cell. Top left position.

**Comment by izcream** [comment]
Get same thing too on v1.0.7

**Comment by andrewdavidcostello** [comment]
I have the same issue, I am using a tooltip inside a modal and the position is always directly over the element setting 0 as top and left positioning.

**Comment by josdirksen** [comment]
I've ran into something the same where in Chrome the vertical position of the popover was incorrect (seemed to be offset with 400px), and it worked in Firefox and IE10. Apparently, in my case, it was caused by rendering the components of this page at different times, which caused the trigger for the popover to move 400px down after it was instantiated.

When you look into the code for the `popoverMixins` it looks like that the position of the popover (or any of the other popup elements I guess) is determined on creation time of the component in the `ready` function. 

```
 ready() {
  ...
    switch (this.placement) {
      case 'top' :
        this.position.left = triger.offsetLeft - popover.offsetWidth / 2 + triger.offsetWidth / 2
        this.position.top = triger.offsetTop  - popover.offsetHeight
        break
      case 'left':
        this.position.left = triger.offsetLeft - popover.offsetWidth
        this.position.top = triger.offsetTop + triger.offsetHeight / 2 - popover.offsetHeight / 2
        break
      case 'right':
        this.position.left = triger.offsetLeft + triger.offsetWidth
        this.position.top = triger.offsetTop + triger.offsetHeight / 2 - popover.offsetHeight / 2
        break
      case 'bottom':
        this.position.left = triger.offsetLeft - popover.offsetWidth / 2 + triger.offsetWidth / 2
        this.position.top = triger.offsetTop + triger.offsetHeight
        break
      default:
        console.log('Wrong placement prop')
    }
```
Acoording to the vue documentation (and the lifecycle diagram http://vuejs.org/guide/instance.html#Lifecycle_Diagram) `ready` is called only when the component is created. So any other updates which might change the position of this element result in popups in incorrect locations. For my own local version I made a quick fix by adding this same logic to the toggle function (in this case I force the top position):

```
	    toggle: function toggle() {
			var popover = this.$els.popover;
			var triger = this.$els.trigger.children[0];
			this.position.top = triger.offsetTop + triger.offsetHeight;
			popover.style.top = this.position.top + 'px';
			this.show = !this.show;
	    }
```

Now each time the toggle is called (either by hovering or clicking) the position of the popup is recalculated and will appear on the correct position. Haven't had the time yet to make a proper pull request, but I can do that if @amanpatel would like that.

**Comment by yuche** [comment]
try this:

<div style="position: relative">
 <tooltip></tooltip>
<div>
在 2016年3月18日 下午2:35:01, Jos Dirksen (notifications@github.com) 写到:

**Comment by josdirksen** [comment]
I tried that, but while this (almost) solves the positioning of the tooltip, it messes up the width (which causes the invalid position I guess):

![image](https://cloud.githubusercontent.com/assets/1381917/13870352/e8aefa48-ecdd-11e5-81bb-0f9b46b32415.png)

The only way I could get this to work properly is by recalculating the position when the element is clicked. But I haven't really explored the width issue.

**Comment by drwebman** [comment]
I have a solution, which tracks the mouse position. Set placement="mouse" in the component and add the following to popoverMixins.js
```
      case 'mouse':
          EventListener.listen(triger, 'mousemove', function(e) {
              this.position.top = e.clientY - triger.offsetHeight
              this.position.left = e.clientX - (popover.offsetWidth / 2)
              this.show = false
              popover.style.top = this.position.top + 'px'
              popover.style.left = this.position.left + 'px'
              this.show = true
          }.bind(this))
          break;
```

and add 
```
    v-bind:class="{
    'top':placement === 'top',
    'left':placement === 'left',
    'right':placement === 'right',
    'bottom':placement === 'bottom',
    'bottom':placement === 'mouse'
    }"
``` in Popover.vue

You may need to add a further adjustment if you have a sidebar by subtracting that from the width,
I did this:
```
              var sidebar = document.getElementById('sidebar')
              this.position.left = e.clientX - sidebar.offsetWidth - (popover.offsetWidth / 2)
```

Hope this helps someone!

**Comment by FgoPan** [comment]
I got the same question 
first time always be top 0px left 0px and turn to the right place very soon
there is a flash during the process

**Comment by kaarthikeyansp** [comment]
+1

**Comment by sshivers** [comment]
I was able to get my popover to position correctly by wrapping the tooltip and button in another div and setting that div as position: relative.

**Comment by charles4201** [comment]
@sshivers +1, same problem, tooltip or popover are the same, they change position of the button

**Comment by wffranco** [comment]
@dojorob76 watching your HTML example, you put tooltips wrapping a single text.
Tooltip & popover work over some the first DOM element they find (div, spam, ul, p or whatever)... so if they don't find it, then don't work properly. 

Try again using at least a spam container to your text.

**Comment by dojorob76** [comment]
@wffranco - Thanks for reaching out. In this case, the popover/tooltip is a Vue Component, and the text is in the <slot></slot>. In normal Bootstrap, you are definitely correct, however, so good looking out. :-)
