### ISSUE TITLE
errors when using webpack and vue-loader

### ISSUE THREAD

**Issue by ablipan** [yuche/vue-strap#9]
**I've got the errors in console after running 'webpack' **
<p style="color:red">
ERROR in ./~/vue-strap/src/main.js
Module parse failed: /Users/Pan/Documents/Js/js framework/Vue/vue-strap/demo/node_modules/vue-strap/src/main.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| export alert from './Alert.vue'
| export carousel from './Carousel.vue'
| export slider from './Slider.vue'
 @ ./~/babel-loader?optional[]=runtime!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue 5:11-31
</p>

**My app.vue**

```javascript
//...
module.exports = {
components:{
    alert: require('vue-strap').alert
  }
//...
}
//...
```
**My webpack.config.js**

```javascript
var vue = require('vue-loader'),
  path = require('path'), //
  nodeRoot = path.join(__dirname, 'node_modules');
module.exports = {
  entry: "./src/main.js",
  output: {
    path: "./build",
    filename: "build.js"
  },
  resolve: {
    root: [nodeRoot]
  },
  module: {
    loaders: [{
      test: /\.vue$/,
      loader: "vue"
    }]
  },
  devtool: 'source-map'
}
```

**Comment by yuche** [comment]
The JavaScript part was writing in ES6.
So, try:
```js
  module: {
    loaders: [
      {
        test: /\.vue$/,
        loader: vue.withLoaders({
          // apply babel transform to all javascript
          // inside *.vue files.
          js: 'babel?optional[]=runtime'
        })
      }
    ]
  },
```

**Comment by ablipan** [comment]
@yuche I've changed my **webpack.config.js** to:

```javascript
var vue = require('vue-loader'),
  path = require('path'), //
  nodeRoot = path.join(__dirname, 'node_modules');
module.exports = {
  entry: "./src/main.js",
  output: {
    path: "./build",
    filename: "build.js"
  },
  resolve: {
    root: [nodeRoot]
  },
  module: {
    loaders: [{
      test: /\.vue$/,
      loader: vue.withLoaders({
        // apply babel transform to all javascript
        // inside *.vue files.
        js: 'babel?optional[]=runtime'
      })
    }, {
      test: /\.css$/,
      loader: 'style-loader!css-loader'
    }, {
      test: /\.woff|.woff2$/,
      loader: "url-loader?prefix=font/&limit=5000&mimetype=application/font-woff"
    }, {
      test: /\.ttf|eot|svg$/,
      loader: "file-loader"
    }]
  },
  devtool: 'source-map'
}
```
**But still get the errors:**

```javascript
ERROR in ./~/vue-strap/src/main.js
Module parse failed: /Users/Pan/Documents/Js/js framework/Vue/vue-strap/demo/node_modules/vue-strap/src/main.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| export alert from './Alert.vue'
| export carousel from './Carousel.vue'
| export slider from './Slider.vue'
 @ ./~/babel-loader?optional[]=runtime!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue 5:11-31
```

**Then  i changed my app.vue to this, it all works except the popover component...**

```javascript
components:{
    alert: require('vue-strap/dist/vue-strap').alert,
    datepicker: require('vue-strap/dist/vue-strap').datepicker,
    modal: require('vue-strap/dist/vue-strap').modal,
    popover: require('vue-strap/dist/vue-strap').popover,
    tabs: require('vue-strap/dist/vue-strap').tabs,
    tab: require('vue-strap/dist/vue-strap').tab
  }
```

**What's more**

```npm run docs``` is invalid, can not find the docs script in package.json

**Comment by yuche** [comment]
@ablipan Sorry, my bad. Now you can use `npm run docs`

Did you get any errors  on your browser console when popover component problem happened?

**Comment by ablipan** [comment]
@yuche no errors in console,and the html looks right... but nothing happened after clicking the button.
![image](https://cloud.githubusercontent.com/assets/4636330/10408894/2e29612c-6f3d-11e5-8ad6-4124f17aa35b.png)

**Comment by yuche** [comment]
@ablipan 
It could be a bug.
Try this:
```html
<div style="position: relative;">
  <popover yourOptions>
    <button>Trigger</button>
  </popover>
</div>
```

**Comment by ablipan** [comment]
@yuche  not working also...
If importing the css in the html using &lt;link&gt; ,the popover works fine.
But if doing that in the app.js using ```require('bootstrap/dist/css/bootstrap.css')``` ,the popover is not working.

**Comment by yuche** [comment]
@ablipan 

I'm glad that you found out this.

Notes You come from China, you may need [babel/polyfill](https://babeljs.io/docs/usage/polyfill/) for better compatibility (IE and 360 browser).

**Comment by ablipan** [comment]
@yuche :smile: thanks
