### ISSUE TITLE
Typeahead component from CDNjs (v1.0.3) prepends "asdf"

### ISSUE THREAD

**Issue by larsandreasness** [yuche/vue-strap#99]
I am dependent on vue-strap as a CDN resource in my project.
The typeahead component from cdnjs.com (v1.0.3) prepends "asdf" on every suggestion.
Rendered:
![image](https://cloud.githubusercontent.com/assets/13853467/12578144/4490211c-c41f-11e5-9e50-31514e90f403.png)
Can't find the reason anywhere in the source code.
Am I missing something? Or am I fethcing an older version than the current? Only using a primitive array as `:data`-binding, as well as a placeholder text.
Possibly, can anyone point me in the direction of a CDN containing the updated version?

**Comment by amanpatel** [comment]
Thanks for this. Looks like I've forgotten to increment the version number in package.json and that has resulted in cdnjs not picking up the latest version (v1.0.6). Fix is coming!
